# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-03 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180503_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_created=True)),
                ('comment_author', models.CharField(max_length=50, verbose_name=b'Name')),
                ('comment_content', models.CharField(max_length=250, verbose_name=b'Comment')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name=b'image:'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
